
language: node_js
node_js:
  - "8"

before_script:
  - npm i codecov -g

script:
  - yarn run build

cache:
  yarn: true

before_deploy:
  - rm -rf release
  - mkdir -p release
  - for file in ./dist/*; do cp "$file" "${file/dist\/vuesax/release/vuesax-${TRAVIS_TAG}}"; done
  - zip -jr "release/vuesax-${TRAVIS_TAG}.zip" release/*

deploy:
  - provider: npm
    email: "luisdaninelrovira8@gmail.com"
    api_key: $NPM_API_KEY
    tag: $(node ./build/parse-npm-tag.js ${TRAVIS_TAG})
    skip_cleanup: true
    on:
      repo: lusaxweb/vuesax
      tags: true
  - provider: releases
    api_key: $GITHUB_API_KEY
    file: "release/vuesax-${TRAVIS_TAG}.zip"
    skip_cleanup: true
    on:
      tags: true
